[build]
  command = "npm run build" # Command to build your Astro site
  publish = "dist"          # Directory to publish (output folder)
  functions = "netlify/functions"

[dev]
  framework = "astro"
  targetPort = 4321

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200

[[plugins]]
package = "netlify-plugin-csp-generator"

  [plugins.inputs]
  buildDir = "dist"

  [plugins.inputs.policies]
    defaultSrc = "'self' cloudfront.net *.cloudfront.net"
    scriptSrc = "'self' 'unsafe-eval' https://js.stripe.com"
    frameSrc = "'self' https://js.stripe.com https://hooks.stripe.com https://app.netlify.com"
    connectSrc = "'self' https://api.stripe.com https://cdn.sanity.io"
    imgSrc = "'self' https: data: https://*.stripe.com https://*.sanity.io"
    styleSrc = "'self' https://cdnjs.cloudflare.com https://fonts.googleapis.com 'style-src-elem' 'style-src-attr'"
    fontSrc = "'self' https: data:"
    upgradeInsecureRequests = true