[build]
  command = "npm run build" # Command to build your Astro site
  publish = "dist"          # Directory to publish (output folder)
  functions = "netlify/functions"

[dev]
  framework = "astro"
  targetPort = 4321

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = '/api/*'
  to = '/.netlify/functions/:splat'
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'nonce-{RANDOM_NONCE}' https://js.stripe.com;
      frame-src 'self' https://js.stripe.com https://hooks.stripe.com;
      connect-src 'self' https://api.stripe.com;
      img-src 'self' https: data:;
      style-src 'self' 'nonce-{RANDOM_NONCE}';
      font-src 'self' https: data:;
      upgrade-insecure-requests;
    '''
